### ISSUE TITLE
Error when 

### ISSUE THREAD

**Issue by sbergotts** [france-connect/identity-provider-example#164]
I get an error when trying to connect with our service provider. The error occurs on the first request to the /user/authorize endpoint:

```
  TypeError: Cannot read property 'stateFor' of undefined
      at processSessionState (C:\dev\identity-provider-example\node_modules\oidc-provider\lib\helpers\process_session_state.js:18:25)
      at Function.saltedProcessSessionState [as salted] (C:\dev\identity-provider-example\node_modules\oidc-provider\lib\helpers\process_session_state.js:43:10)
      at authorizationErrorHandler (C:\dev\identity-provider-example\node_modules\oidc-provider\lib\shared\authorization_error_handler.js:97:52)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async ensureSessionSave (C:\dev\identity-provider-example\node_modules\oidc-provider\lib\helpers\initialize_app.js:42:7)
      at async contextEnsureOidc (C:\dev\identity-provider-example\node_modules\oidc-provider\lib\shared\context_ensure_oidc.js:4:5)
```

The only thing I have changed was the redirect uri. How can I get around this issue?

**Comment by 06dede06** [comment]
session var empty ...
